Feature exception
AsahiSasaki/TaskManager pull request #2
Opened 2024-03-01 08:39 UTC by AsahiSasaki

追加要件
2. DB操作失敗時などの例外ハンドリングを設計＆実装する。
対応完了他ので、確認よろしくお願いします。

2024-03-05 14:56 UTC, shota-ootani-excite requested changes

2024-03-05 14:56 UTC, shota-ootani-excite commented on src/main/java/com/excite/taskmanager/domain/object/TaskObject.java
> +    public int id;
publicではなく、privateが正しいですよ。
カプセル化ってやつです。

2024-03-05 14:56 UTC, shota-ootani-excite commented on src/main/java/com/excite/taskmanager/application/controller/TaskController.java
> +            throw new TaskNotExistException(id);
serviceまたはrepositoryでthrowして良いと思います。
他APIも同様です。

2024-03-05 14:56 UTC, shota-ootani-excite commented on src/main/java/com/excite/taskmanager/domain/service/TaskService.java
> +        TaskValidation.validate(data);
domain層に来る前のapplication層で入力チェックして良いと思います。

2024-03-05 14:56 UTC, shota-ootani-excite commented on src/main/java/com/excite/taskmanager/application/controller/TaskController.java
> +    public ResponseEntity<String> createTask(@RequestBody TaskPostBody taskPostBody) throws ValidationException {
レスポンスをvoidからstringに変更した意図はなんでしょうか？

2024-03-06 04:19 UTC, AsahiSasaki commented on src/main/java/com/excite/taskmanager/domain/object/TaskObject.java
> +    public int id;
ご指摘の通り、privateに直しました。
TaskValidationで、TaskObjectのフィールドに直接アクセスしていたのを、getterを使用して取得するように修正しました。

2024-03-06 04:20 UTC, AsahiSasaki commented on src/main/java/com/excite/taskmanager/application/controller/TaskController.java
> +            throw new TaskNotExistException(id);
指摘通り対応しました。

2024-03-06 04:20 UTC, AsahiSasaki commented on src/main/java/com/excite/taskmanager/domain/service/TaskService.java
> +        TaskValidation.validate(data);
指摘通り対応しました。

2024-03-06 04:21 UTC, AsahiSasaki commented on src/main/java/com/excite/taskmanager/application/controller/TaskController.java
> +    public ResponseEntity<String> createTask(@RequestBody TaskPostBody taskPostBody) throws ValidationException {
はじめResponseBodyにエラーメッセージを入れて、返すようにしていて、その後、現在の実装に修正したのですが、
その際に直し忘れていました。voidのままでよかったです。

2024-03-06 14:18 UTC, shota-ootani-excite approved these changes

2024-03-07 00:01 UTC, merged