Feature open api
AsahiSasaki/TaskManager pull request #3
Opened 2024-03-13 08:17 UTC by AsahiSasaki

追加要件
3. 作成したAPIをOpenAPI （Swagger）のyaml形式でドキュメント化する。
4. openapi generatorを使用して、APIのIF部品を自動生成してみる。
対応完了

2024-03-14 14:22 UTC, shota-ootani-excite requested changes

2024-03-14 14:22 UTC, shota-ootani-excite commented on src/main/java/com/excite/taskmanager/application/controller/TaskController.java
> +    // /**
javadocがコメントアウトされているような状態なので修正ください。

2024-03-14 14:22 UTC, shota-ootani-excite commented on src/main/java/com/excite/taskmanager/application/controller/TaskController.java
> +    public ResponseEntity<Void> createTask(@Valid TaskPostBody taskPostBody) throws Exception {
throwsがValidationExceptionからExceptionに変えた理由を教えてください。

2024-03-14 14:22 UTC, shota-ootani-excite commented on src/main/resources/taskApi.yaml
> +          type: integer
statusについても、未完了or完了のチェックができると思います。
正規表現かenumかなと思いますが、調べて実装してみてください。

2024-03-14 14:22 UTC, shota-ootani-excite commented on src/main/java/com/excite/taskmanager/domain/service/TaskValidation.java
>  public class TaskValidation {
今更の指摘になってしまいますが、serviceフォルダに置くのであれば、TaskServiceと同じようにServiceとして実装してください。
そうではなくstaticメソッドを提供するユーティリティクラスとしたいのであれば、application、domainフォルダと同じ階層に「common」などの名前でフォルダを作成して、そこに置いてください。

2024-03-15 07:26 UTC, AsahiSasaki commented on src/main/java/com/excite/taskmanager/application/controller/TaskController.java
> +    // /**
指摘通り修正しました。

2024-03-15 07:29 UTC, AsahiSasaki commented on src/main/java/com/excite/taskmanager/application/controller/TaskController.java
> +    public ResponseEntity<Void> createTask(@Valid TaskPostBody taskPostBody) throws Exception {
入力補完を使うと、Exceptionとなっていて、他のメソッドについては手で、TaskNotExistException,ValidationExceptionと
直していたのを、createTaskについては直していなかったので、ExceptionからValidationExceptionに修正しました。

2024-03-15 07:31 UTC, AsahiSasaki commented on src/main/resources/taskApi.yaml
> +          type: integer
enumを使って、statusのバリデーションも行えるようにしました。
それに伴って、modelMapperにInteger→EnumStatusの変換処理を記述しました。

2024-03-15 07:32 UTC, AsahiSasaki commented on src/main/java/com/excite/taskmanager/domain/service/TaskValidation.java
>  public class TaskValidation {
ご指摘の通り、commonフォルダに移動しました。

2024-03-19 00:55 UTC, shota-ootani-excite approved these changes

2024-03-19 01:56 UTC, merged