Feature integration test
AsahiSasaki/TaskManager pull request #5
Opened 2024-03-25 08:06 UTC by AsahiSasaki

追加要件
6. JUnit＋DBUnitでバックエンドの結合テスト（API単位）を実装する。
mockMVCでAPIを呼び出すテスト実装をする。

2024-03-27 08:43 UTC, shota-ootani-excite requested changes

2024-03-27 08:43 UTC, shota-ootani-excite commented on src/test/java/com/excite/taskmanager/integrationTest/IntegrationTest.java
> +                .andExpect(status().isOk())
直さなくて良いです。

.andReturn()でレスポンスを取得できます。
項目が多くなるとandExpectのchainでテストするのはしんどいと思うので、andReturn()に統一するのが良いです。

現場ではexpectedにjson文字列をセットして、レスポンスボディ全体をテストしています。

2024-03-27 08:43 UTC, shota-ootani-excite commented on src/test/java/com/excite/taskmanager/integrationTest/IntegrationTest.java
> +    public void testGetTasks() throws Exception {
すべてのAPIのテストが同じ階層に書かれているので、このファイルの中でさらにclassを分けた方が見やすいです。
Nestedアノテーションを調べてみてください。

2024-03-27 08:43 UTC, shota-ootani-excite commented on src/test/java/com/excite/taskmanager/integrationTest/IntegrationTest.java
> +    public void testCreateTask_Success() throws Exception {
タスク登録後のデータベースが期待結果通りであるか、テストしてみてください。
DBUnitで調べるとやり方が出てくると思います。
更新・削除のAPIも同様です。

2024-03-29 04:13 UTC, AsahiSasaki commented on src/test/java/com/excite/taskmanager/integrationTest/IntegrationTest.java
> +                .andExpect(status().isOk())
ありがとうございます。
参考にします。

2024-03-29 04:13 UTC, AsahiSasaki commented on src/test/java/com/excite/taskmanager/integrationTest/IntegrationTest.java
> +    public void testGetTasks() throws Exception {
指摘通り対応しました。

2024-03-29 04:15 UTC, AsahiSasaki commented on src/test/java/com/excite/taskmanager/integrationTest/IntegrationTest.java
> +    public void testCreateTask_Success() throws Exception {
指摘通り対応しました。
auto_incrementになっているIDですが、制御する方法が見つからなかったので、createTaskの際は、
IDカラムを除いて比較するようにしました。

2024-03-29 07:04 UTC, shota-ootani-excite approved these changes

2024-03-29 07:15 UTC, merged